mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  config: utf-8mb4
  user: root
  passwd: Air4045@
  log_level: debug
logger:
  level: info
  prefix: gvb
  director: log
  showline: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site_info:
  title: 孤独的人的博客
  createDate: "2024-2-18"
  version: "1.0"
upload:
  photoSize: 10
  photoPath: uploads/photos
  videoSize: 10240
  videoPath: uploads/videos
  fileSize: 1024
  filePath: uploads/files
